inherit_from:
  - config/rubocop/rspec.yml
  - config/rubocop/rails.yml
  - config/rubocop/rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  DisplayCopNames: true
